package tn.esprit.AppMobile;



import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import tn.esprit.AppMobile.GUI.Feedback.AddFeedback;
import tn.esprit.AppMobile.GUI.Feedback.ListFeedback;
import tn.esprit.AppMobile.GUI.Feedback.UpdateFeedback;
import tn.esprit.AppMobile.GUI.Home;
import tn.esprit.AppMobile.GUI.offre.AfficherOffre;
import tn.esprit.AppMobile.GUI.produit.ListProduitForm;
import tn.esprit.AppMobile.GUI.reclamation.AddReclamation;
import tn.esprit.AppMobile.GUI.reclamation.Feedbacks;
import tn.esprit.AppMobile.GUI.reclamation.ListReclamations;
import tn.esprit.AppMobile.GUI.recrutement.GererRecrutement;
import tn.esprit.AppMobile.GUI.recrutement.ListRecrutements;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    public static Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }

        if(SessionManager.getNomUser()==null){
            new LoginForm(theme).show();
        }else     
        new DashIndex(theme).show();
           // new ListReclamations(theme).show();
           // new AddFeedback(theme).show();
            // new AddReclamation(theme).show();            
            // new Feedbacks(theme).show();
           //  new ListFeedback (theme).show();
            // new UpdateFeedback(theme).show();    
           // new ListRecrutements(theme).show();
           // new GererRecrutement(theme).show();
           //  new ListProduitForm(theme).show();
            
           // new AfficherOffre(theme).show();
      
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
